sonar.projectKey=dcos-platform_cert-orchestrator-service
sonar.organization=dcos-platform-sonar-key
sonar.sources=cert_orchestrator
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true
